# Cargo configuration for genomic cryptanalysis project

[build]
# Number of parallel jobs (adjust based on your system)
jobs = 8

[target.x86_64-unknown-linux-gnu]
# Linux-specific linker settings for CUDA
rustflags = ["-C", "link-arg=-Wl,-rpath,$ORIGIN/../lib"]

[target.x86_64-pc-windows-msvc]
# Windows-specific settings
rustflags = ["-C", "target-feature=+crt-static"]

[env]
# Default CUDA compute capability for GTX 2070
NVCC_COMPUTE_CAPS = "75"

# Development environment variables
RUST_LOG = "genomic_cryptanalysis=debug"

[alias]
# Convenient aliases for CUDA development
cuda-build = "build --features cuda"
cuda-test = "test --features cuda"
cuda-bench = "bench --features cuda"
cuda-run = "run --features cuda"

# Release builds with CUDA
cuda-release = "build --release --features cuda"
cuda-release-run = "run --release --features cuda"

# Debug builds with extra info
cuda-debug = "build --features cuda-debug"

# Check CUDA code without building
cuda-check = "check --features cuda"