global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Coordinator metrics
  - job_name: 'coordinator'
    static_configs:
      - targets: ['coordinator:8080']
    metrics_path: '/metrics'

  # Redis exporter (if added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # Agent metrics (exposed via coordinator)
  - job_name: 'agents'
    static_configs:
      - targets: ['coordinator:8080']
    metrics_path: '/agent-metrics'

  # Docker metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']